### ISSUE TITLE
Accessing Central Dashboard

### ISSUE THREAD

**Issue by aba-ca-xi** [argoflow/argoflow#101]
/kind question 

Hello everyone, 

I've gone through the steps to fork the repo  and apply the components I need as outlined in the readme. However, I'm having some issues configuring the dashboard. I want to setup an ingress gateway that forwards the request from the external load balancer to the service that hosts the dashboard. I'm just unclear what destination host to use to achieve this. 

Please let me know if I can clarify my question further. 

Thanks in advance!

**Comment by DavidSpek** [comment]
Hi there. Firstly I'd like to point out that there will be rather large change in the repo structure shortly to add all sorts of improvements. Just so can keep this in mind.

What issues are you facing exactly? Are you using MetalLB or another type of load balancer? You shouldn't need to set up an ingress as Istio is used for this.

**Comment by aba-ca-xi** [comment]
Hey David, 

Thanks for the prompt reply. Internally, we manage our deployment of istio. I've confirmed that the installation works by running a simple application akin to httpbin. I have an istio gateway setup through this installation and I'd like to specify a virtual service that includes the host the user should hit to get to the central dashboard.  I'm unclear what the route's host should be: 

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: centraldashboard-ui
spec:
  hosts:
  - <External URL>
  gateways:
  - istio-system/gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: <Where should the request be routed to?>

```

I am not using MetalLB in our deployment and I'm unsure of any other way to expose the dashboard. The documentation states that one should log in with the default credentials when the istio-ingressgateway has been successfully setup. 

I've setup a kubeflow cluster via the GCP instructions provided by kubeflow and they automatically setup a url with which you can reach the central dashboard by configuring Ingress. I've isolated the manifest that does this below:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false" 
    kubernetes.io/ingress.global-static-ip-name: $(ipName)
    networking.gke.io/managed-certificates: gke-certificate
  name: envoy-ingress
spec:
  backend:
    serviceName: istio-ingressgateway
    servicePort: 80
  rules:
  - host: $(hostname)
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /*

```

I'd like to do something similar if possible. Thanks again for your assistance!
