### ISSUE TITLE
authn-filter not syncing

### ISSUE THREAD

**Issue by ranzbak** [argoflow/argoflow#116]
When I try to get the Envoy filter to apply I get the following error :+1: 

error validating data: ValidationError(EnvoyFilter.spec.configPatches[0]): unknown field "listener" in io.istio.networking.v1alpha3.EnvoyFilter.spec.configPatches

The following part does not apply, starting at line 33

```
listener:
  filterChain:
    filter:
     name: envoy.http_connection_manager
     subFilter:
       name: ''
```

I'm not sure why this is, and what I did wrong to get this error.

Running on Kubernetes RKE 1.20.6 on Ubuntu 20.10
ArgoCD v2.0.3+8d2b13d
